-- ============================================
-- Projek_DPSI - Supabase Restore Script
-- ============================================
-- 
-- Apa yang di-restore:
--   ✅ Semua definisi tabel (CREATE TABLE)
--   ✅ Fungsi (handle_new_user, update_user_points)
--   ✅ Data games preset (4 game bawaan)
--   ✅ Data quizzes, quiz_questions, quiz_options
--   ✅ Primary keys, constraints, foreign keys
--   ✅ Row Level Security
-- 
-- Apa yang TIDAK di-restore (tidak bisa dipindah):
--   ❌ profiles (bergantung pada auth.users)
--   ❌ classes (bergantung pada profiles)
--   ❌ class_members (bergantung pada profiles)
--   ❌ class_assignments (bergantung pada classes)
--   ❌ user_activities (bergantung pada auth.users)
--   ❌ custom games (dibuat oleh teacher yang perlu daftar ulang)
--
-- Setelah restore: semua anggota tim daftar ulang →
-- profil baru otomatis dibuat via trigger handle_new_user()
-- ============================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ============================================
-- FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  insert into public.profiles (id, full_name, role, total_points, point_achievement, games_played, badge)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'student',
    0,
    0,
    0,
    'Bronze'
  );
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.update_user_points(user_id_input uuid, points_to_add integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
  update public.profiles
  set
    total_points = total_points + points_to_add,
    games_played = games_played + 1
  where id = user_id_input;
end;
$$;

-- ============================================
-- TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS public.class_assignments (
    class_id uuid NOT NULL,
    game_id uuid NOT NULL,
    assigned_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.class_members (
    class_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    joined_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.classes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    class_name text NOT NULL,
    description text,
    class_code text NOT NULL,
    teacher_id uuid
);

CREATE TABLE IF NOT EXISTS public.custom_game_questions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    game_id uuid,
    question_text text,
    image_url text,
    correct_answer text[]
);

CREATE TABLE IF NOT EXISTS public.custom_game_word_bank (
    id bigint NOT NULL,
    question_id uuid,
    word text NOT NULL
);

ALTER TABLE public.custom_game_word_bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_game_word_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS public.games (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text,
    category text,
    level text,
    gradient text,
    image text,
    path text,
    teacher_id uuid,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL,
    full_name text,
    role text DEFAULT 'student'::text,
    total_points integer DEFAULT 0,
    point_achievement integer DEFAULT 0,
    last_claimed_day integer,
    games_played integer DEFAULT 0,
    badge text DEFAULT 'Bronze'::text
);

CREATE TABLE IF NOT EXISTS public.quiz_options (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    question_id uuid,
    option_text text NOT NULL,
    is_correct boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    quiz_id uuid,
    question_text text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quizzes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_activities (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    activity_type text,
    start_date date DEFAULT now(),
    status integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.user_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ============================================
-- DATA: Games Preset (tidak bergantung pada user)
-- ============================================

INSERT INTO public.games (id, title, description, category, level, gradient, image, path, teacher_id, created_at)
VALUES
    ('a1b2c3d4-0001-4001-8001-000000000001', 'Body word structure', NULL, 'Puzzle', 'Easy, 10 Questions', 'from-pink-400 to-red-500', 'https://yztecwcdxpdqmfmmddhn.supabase.co/storage/v1/object/public/game-assets/bodyword.jpg', '/puzzle-lobby/body-word-structure', NULL, '2025-07-10 01:46:16.043546+00'),
    ('a1b2c3d4-0002-4002-8002-000000000002', 'Simple past tense', NULL, 'Puzzle', 'Medium, 15 Questions', 'from-yellow-400 to-orange-500', 'https://yztecwcdxpdqmfmmddhn.supabase.co/storage/v1/object/public/game-assets/simplepast.jpg', '/puzzle-lobby/simple-past-tense', NULL, '2025-07-10 01:46:16.043546+00'),
    ('a1b2c3d4-0003-4003-8003-000000000003', 'Fruity', NULL, 'Crossword', 'Easy, 20 Questions', 'from-purple-500 to-pink-600', 'https://yztecwcdxpdqmfmmddhn.supabase.co/storage/v1/object/public/game-assets/fruitty.jpg', '/puzzle-lobby/fruity', NULL, '2025-07-10 01:46:16.043546+00'),
    ('a1b2c3d4-0004-4004-8004-000000000004', 'Place value', NULL, 'Crossword', 'Easy, 10 Questions', 'from-blue-400 to-purple-600', 'https://yztecwcdxpdqmfmmddhn.supabase.co/storage/v1/object/public/game-assets/placevalue.jpg', '/puzzle-lobby/place-value', NULL, '2025-07-10 01:46:16.043546+00');

-- ============================================
-- PRIMARY KEYS & CONSTRAINTS
-- ============================================

ALTER TABLE ONLY public.class_assignments
    ADD CONSTRAINT class_assignments_pkey PRIMARY KEY (class_id, game_id);

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_pkey PRIMARY KEY (class_id, user_id);

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_class_code_key UNIQUE (class_code);

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.custom_game_questions
    ADD CONSTRAINT custom_game_questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.custom_game_word_bank
    ADD CONSTRAINT custom_game_word_bank_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.quiz_options
    ADD CONSTRAINT quiz_options_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_activities
    ADD CONSTRAINT user_activities_pkey PRIMARY KEY (id);

-- ============================================
-- FOREIGN KEYS
-- ============================================

ALTER TABLE ONLY public.class_assignments
    ADD CONSTRAINT class_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.class_assignments
    ADD CONSTRAINT class_assignments_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id);

ALTER TABLE ONLY public.custom_game_questions
    ADD CONSTRAINT custom_game_questions_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.custom_game_word_bank
    ADD CONSTRAINT custom_game_word_bank_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.custom_game_questions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.quiz_options
    ADD CONSTRAINT quiz_options_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.quiz_questions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_activities
    ADD CONSTRAINT user_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE public.class_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_game_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_game_word_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_activities ENABLE ROW LEVEL SECURITY;

-- ============================================
-- TRIGGER: handle_new_user
-- Otomatis membuat profil saat user mendaftar
-- ============================================

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
